[package]
name = "bloom-filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
fnv = "1.0.3"
fxhash = "0.2.1"
sha2 = "0.10.2"
